version: "2"
services:
  ksql-server:
    image: confluentinc/cp-ksql-server:5.3.1
    expose:
      - "8088"
    environment:
      KSQL_BOOTSTRAP_SERVERS: kafka:9092
      KSQL_LISTENERS: http://0.0.0.0:8088
      KSQL_KSQL_SERVICE_ID: ksql_service_1_
      KSQL_KSQL_EXTENSION_DIR: /etc/ksql-server/ext
    volumes:
      - /home/chonk/ext:/etc/ksql-server/ext

  ## CLI is just for testing purposes
  ksql-cli:
    image: confluentinc/cp-ksql-cli:5.3.1
    container_name: ksql-cli
    depends_on:
      - ksql-server
    entrypoint: /bin/sh
    tty: true


networks:
  default:
    external:
      name: titan-ccp-demo_default
